### ISSUE TITLE
Spring Sprint Housekeeping

### ISSUE THREAD

**Issue by Sakshi-Handa** [HumanExposure/factotum#2262]
## Testing

- [x] list_presence filtering test Related to #2272

- [x] add back in 
```
def test_anonymous_tag_suppression(self):
        self.client.logout()
        p = Product.objects.get(pk=878)
        response = self.client.get("/product/878/")
        lxml = html.fromstring(response.content.decode("utf8"))
        for tag in p.get_puc_tags():
            elem = lxml.xpath(f'//ul[@data-tag-name="{tag.name}"]')
            self.assertEqual(len(elem), 0)
```

## Clean up Features

- [x]  Related to #2234 (display of attributes for guest) remove the text and link to admin panel that appears when there are no attributes assigned to a product. 

- [x]  Related to #2236 (QA verified checkbox), move the checkbox over to the left. 

- [x]  Related to #2236 (QA verified checkbox) add qa notes to save success message

## Misc
- investigate neat modules/builtins
- business logic learning 
- SOP review 
- shadowing scientists for learning osmosis

**Comment by hausman-gdit** [comment]
@Sakshi-Handa for this
>(display of attributes for guest) **_remove the text_** and link to admin panel that appears when there are no attributes assigned to a product.

Did you want it to just leave the `(edit)` link in and remove the `No attributes are associated with this PUC` text?

**Comment by Sakshi-Handa** [comment]
> @Sakshi-Handa for this
> 
> > (display of attributes for guest) **_remove the text_** and link to admin panel that appears when there are no attributes assigned to a product.
> 
> Did you want it to just leave the `(edit)` link in and remove the `No attributes are associated with this PUC` text?

Remove both the text and the (edit) link. because it links to the admin panel, and Guest users don't have access to that anyway.

**Comment by hausman-gdit** [comment]
> and Guest users don't have access to that anyway.

Yes, for guests show nothing, but for logged in users do you still want the text and admin panel link?
